### ISSUE TITLE
Json format is expected

### ISSUE THREAD

**Issue by Preethamraj553** [barnumbirr/ares#6]
> from ares import CVESearch
>>> cve = CVESearch()
>>> cve.search('postgresql/postgresql')
JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

**Comment by barnumbirr** [comment]
Hello,

thank you for reporting this. `ares` seems to be broken for now but I'll try to get a new release out this week to fix it.

Cheers.

**Comment by barnumbirr** [comment]
v0.6.0 has been released on Pypi and should fix the issue you're running into. Give it a spin 😉
