### ISSUE TITLE
Some functionalities disabled

### ISSUE THREAD

**Issue by ivanfr90** [barnumbirr/ares#7]
Hi!

Why some functions has been disabled? 

```
# def link(self, param):
#    return self.__request('link/', query=param)

# def search(self, param):
#    return self.__request('search/', query=param)
```

I'm trying to use the **cve.circl.lu** public API to search by vendor and product but I get a 404 response, and later I have seen in your code that some of this functionalities have been disabled. Is there any reason for it?

Thanks!

**Comment by barnumbirr** [comment]
Hello,

these functions have been disabled in the CIRCL API because of abuse. `search` is unfortunately one of these disabled endpoints. ([here's a direct example](https://cve.circl.lu/api/search/microsoft/office))

Hope this answers your questions.

Cheers.

**Comment by ivanfr90** [comment]
I understand, it is what I was thinking...

A solution for this could be reserve your own resourcers and use the [cve-search project](http://cve-search.org/) wich allow to maintain and update your own database with the latest CVE updates.

Do you have any experience with this project [cve-search repository]( https://github.com/cve-search/cve-search)?

Thanks so much @barnumbirr!

**Comment by barnumbirr** [comment]
Hey,

I haven't spun up my own instance but the README seems to ship with a lot of instructions so it shouldn't be too hard.

Cheers.

**Comment by ivanfr90** [comment]
Yeah, you're right. 
I installed the cve-search on my own server. I am currently thinking of using it in a final production service and wanted to check someone's experience.

Sorry for the offtopic, and thanks for everything!! :)

**Comment by barnumbirr** [comment]
Hey,

no worries and good luck. I'll close the issue but don't hesitate to open a nw one if you need any help.

Cheers.
