### ISSUE TITLE
CVESearch doesn't have search api

### ISSUE THREAD

**Issue by sunilkjc2000** [barnumbirr/ares#8]
Followed the instructions provided and tried to access cve.search(). Got below error post accessing search()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'CVESearch' object has no attribute 'search'

**Comment by sunilkjc2000** [comment]
search and link apis are commented in source : # def link(self, param):
	# 	return self.__request('link/', query=param)

	# def search(self, param):
	# 	return self.__request('search/', query=param)

**Comment by barnumbirr** [comment]
[Some API endpoints have been removed from the public instance](https://www.circl.lu/services/cve-search/#public-web-api-of-cve-search) due to massive abusive behavior. You can use this API against a local version of CVE Search.
